### PR TITLE
added card model

### PR DESCRIPTION
**Pull request by ender554**
please review pull request, if it looks good accept if not advise

### CODE REVIEW

**Comment by jdenholtz** [comment]
Looks good to me, may not need to keep cards in database.

**Comment by govtcud** [comment]
I would probably make suit an enum instead:
`enum suit: [:clubs, :diamonds, :hearts, :spades]`

Then the suit is internally stored as an integer instead of a string, which is cheaper, plus it enforces the correctness of suit (unless we want to allow some extra suits? Like stars?), and you also automagically get methods like card.suit (returns name as string, like 'spades' or 'clubs'), plus methods like card.spades? (returns true or false), although I'm not sure how useful that would be.

We could also use an enum for rank, although I'm still thinking about how to treat the high and low ace, and we would either need to specify the values or have a placeholder for rank zero.
For example: `enum rank: {T: 10, J: 11, ...}`, this might be unnecessary and I will have to play around with it.

All that aside, I would really like to get a start on the spec.  Writing good test cases will let us make sure we don't break things as we go.

**Comment by ender554** [comment]
I did not know ruby had enum, but yeah that would be better.

**Comment by govtcud** [comment]
technically it's a Rails thing: http://api.rubyonrails.org/classes/ActiveRecord/Enum.html

**Pull request merged**
